### ISSUE TITLE
Example: text game “A Dark Room”

### ISSUE THREAD

**Issue by loretoparisi** [princeton-nlp/calm-textgame#2]
I have found this text adventure ["A Dark Room - A Minimalist Text Adventure"](https://github.com/doublespeakgames/adarkroom)

I would like to tweak this game with CALM. Which would be the right starting point?

Thanks!

**Comment by ysymyth** [comment]
Hi Loreto! If you want to train RL on this game, you might need to find the z3/z5 simulator file for Jericho to operate, or implement your own RL environment. If you just want to see pertrained CALM prediction for game observations, check out 
"To quickly try out the GPT-2 CALM model" item in the readme.
